//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveMessage
    {
        public int MsgId { get; set; }
        public int AuthorId { get; set; }
        public int MemberId { get; set; }
        public string MsgContent { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public bool IsReply { get; set; }
        public string IP { get; set; }
    }
}
