//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Members
    {
        public int MemberId { get; set; }
        [Display(Name = "会员账号")]
        [Required(ErrorMessage = "请输入会员账号")]//表示必须要输入。
        public string MemberAccount { get; set; }
        [Display(Name = "头像")]
        public string Portrait { get; set; }
        [Display(Name = "昵称")]
        public string NickName { get; set; }
        [Display(Name = "性别")]
        public string Gender { get; set; }
        [Display(Name = "年龄")]
        [Required(ErrorMessage = "请输入年龄")]
        [RegularExpression(@"^[1-9](\d{1,2})?$", ErrorMessage = "请输入正确的年龄")]
        [Range(1, 100, ErrorMessage = "年龄太大或太小")]//该步骤实际上可以在一个正则表达式中完成。
        public Nullable<int> Age { get; set; }
        [RegularExpression(@"^[1-9][0-9]{4,}$", ErrorMessage = "请输入正确的QQ号")]
        public string QQ { get; set; }
        [RegularExpression(@"^w+([-+.]w+)*@w+([-.]w+)*.w+([-.]w+)* $", ErrorMessage = "请输入正确的Email")]
        public string Email { get; set; }
        public Nullable<System.DateTime> RegisterTime { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public string LastLoginIP { get; set; }
        [Required(ErrorMessage = "密码不能为空")]
        [Display(Name = "密码")]
        public string Password { get; set; }


    }
}
