//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    
    public partial class ReplyList
    {
        public Nullable<long> RowIndex { get; set; }
        public int MemberId { get; set; }
        public string MemberAccount { get; set; }
        public string Password { get; set; }
        public string Portrait { get; set; }
        public string NickName { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Age { get; set; }
        public string QQ { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> RegisterTime { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public string LastLoginIP { get; set; }
        public int MsgId { get; set; }
        public int AuthorId { get; set; }
        public string MsgContent { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string IP { get; set; }
        public int ReplyId { get; set; }
    }
}
